import jsPDF from "jspdf";

// Generates a short, boarding-pass-style random reference, e.g. "TB-8F2K9Q"
export const generateBookingRef = () =>
  `TB-${Date.now().toString(36).toUpperCase().slice(-4)}${Math.random()
    .toString(36)
    .toUpperCase()
    .slice(2, 6)}`;

const BRAND_TEAL = [30, 108, 122]; // approximates the app's oklch teal primary
const BRAND_CORAL = [230, 126, 90]; // approximates the app's oklch coral accent
const INK = [30, 41, 59];
const MUTED = [100, 116, 139];

// Renders the shared "this is a demo, not a real purchase" disclaimer band.
// Both document types call this — it's the honest, load-bearing part of
// generating something that otherwise looks like a real booking document.
const drawDemoDisclaimer = (doc, x, y, width) => {
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(
    "DEMO BOOKING — Generated by the TravelBuddy project. No real payment was processed and no real reservation exists.",
    x,
    y,
    { maxWidth: width },
  );
};

export const generateFlightTicket = ({
  passengerName,
  destination,
  flight,
  travelDate,
  bookingRef,
}) => {
  const doc = new jsPDF({ unit: "mm", format: [210, 95], orientation: "landscape" });
  const seat = `${Math.floor(Math.random() * 28) + 1}${"ABCDEF"[Math.floor(Math.random() * 6)]}`;

  // Header band
  doc.setFillColor(...BRAND_TEAL);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(undefined, "bold");
  doc.text("TravelBuddy", 10, 14);
  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.text("Boarding Pass", 190, 14, { align: "right" });

  // Main body
  doc.setTextColor(...INK);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("PASSENGER", 10, 32);
  doc.text("FLIGHT", 90, 32);
  doc.text("BOOKING REF", 160, 32);

  doc.setFontSize(13);
  doc.setTextColor(...INK);
  doc.setFont(undefined, "bold");
  doc.text(passengerName || "Guest Traveler", 10, 39);
  doc.text(flight.flightNumber, 90, 39);
  doc.text(bookingRef, 160, 39);

  doc.setDrawColor(220, 220, 220);
  doc.line(10, 46, 200, 46);

  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("FROM", 10, 55);
  doc.text("TO", 60, 55);
  doc.text("DEPARTS", 110, 55);
  doc.text("ARRIVES", 150, 55);

  doc.setFontSize(12);
  doc.setTextColor(...INK);
  doc.setFont(undefined, "bold");
  doc.text(flight.from, 10, 62);
  doc.text(destination, 60, 62);
  doc.text(flight.departTime, 110, 62);
  doc.text(flight.arriveTime, 150, 62);

  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${flight.airline} • ${flight.duration}`, 10, 70);

  doc.setTextColor(...MUTED);
  doc.text("DATE", 10, 80);
  doc.text("SEAT", 60, 80);
  doc.text("FARE PAID", 110, 80);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...INK);
  doc.text(travelDate || "—", 10, 86);
  doc.text(seat, 60, 86);
  doc.setTextColor(...BRAND_CORAL);
  doc.text(`$${flight.price}`, 110, 86);

  drawDemoDisclaimer(doc, 10, 92, 190);

  doc.save(`TravelBuddy_Flight_${bookingRef}.pdf`);
};

export const generateStayReceipt = ({
  guestName,
  destination,
  stay,
  checkInDate,
  nights,
  bookingRef,
}) => {
  const doc = new jsPDF({ unit: "mm", format: "a5" });
  const total = stay.pricePerNight * nights;

  doc.setFillColor(...BRAND_TEAL);
  doc.rect(0, 0, 148, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(undefined, "bold");
  doc.text("TravelBuddy", 10, 14);
  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.text("Stay Receipt", 138, 14, { align: "right" });

  doc.setTextColor(...MUTED);
  doc.setFontSize(9);
  doc.text("GUEST", 10, 32);
  doc.text("BOOKING REF", 90, 32);
  doc.setFontSize(12);
  doc.setTextColor(...INK);
  doc.setFont(undefined, "bold");
  doc.text(guestName || "Guest Traveler", 10, 39);
  doc.text(bookingRef, 90, 39);

  doc.setDrawColor(220, 220, 220);
  doc.line(10, 46, 138, 46);

  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("PROPERTY", 10, 55);
  doc.setFontSize(12);
  doc.setTextColor(...INK);
  doc.setFont(undefined, "bold");
  doc.text(stay.name, 10, 62);
  doc.setFont(undefined, "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${stay.type} • ${destination}`, 10, 68);

  doc.text("CHECK-IN", 10, 80);
  doc.text("NIGHTS", 60, 80);
  doc.text("RATE / NIGHT", 95, 80);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...INK);
  doc.text(checkInDate || "—", 10, 86);
  doc.text(String(nights), 60, 86);
  doc.text(`$${stay.pricePerNight}`, 95, 86);

  doc.setDrawColor(220, 220, 220);
  doc.line(10, 94, 138, 94);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.setFont(undefined, "normal");
  doc.text("TOTAL PAID", 10, 102);
  doc.setFontSize(14);
  doc.setTextColor(...BRAND_CORAL);
  doc.setFont(undefined, "bold");
  doc.text(`$${total}`, 40, 102);

  drawDemoDisclaimer(doc, 10, 112, 128);

  doc.save(`TravelBuddy_Stay_${bookingRef}.pdf`);
};